onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - msgpackr-extract
  - prisma
overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  tmp@<=0.2.3: '>=0.2.4'
